### ISSUE TITLE
unhandled nil check_tar_result

### ISSUE THREAD

**Issue by jantman** [manheim/backupsss#5]
```
Create and Upload Tar: Starting
tar command stderr:
tar: Removing leading `/' from member names
tar (child): /backup/1483470540.tar: Cannot open: No space left on device
tar (child): Error is not recoverable: exiting now
ERROR - backup failed: undefined method `nonzero?' for nil:NilClass
backupsss-0.2.0/lib/backupsss/tar.rb:23:in `check_tar_result'
backupsss-0.2.0/lib/backupsss/tar.rb:18:in `make'
```

Looks like in [check_tar_result](https://github.com/manheim/backupsss/blob/edbedfcaeac46b44ef342d17bb64cbf05cb3ca7f/lib/backupsss/tar.rb#L23) we're doing ``if status.exitstatus.nonzero?``, but it's possible for a failed run to return a nil ``exitstatus``. We need to check for that.

While we're in that section of the code, it's probably useful (for errors like the above) to log the full tar command we're running _before_ it's run.

**Comment by jantman** [comment]
This was fixed by #8
